repositories:
- name: stable
  url: https://charts.helm.sh/stable/

releases:

- name: fibo
  chart: ./charts/app
  values:
  - ./values/fibo.yaml

- name: myservice
  chart: ./charts/app
  values:
  - ./values/myservice.yaml

- name: ingress-backend
  chart: stable/nginx-ingress
  version: 1.36.0

- name: ingress-controller
  chart: ./charts/ingress
  values:
  - ./values/ingress.yaml