environments:
  default:
    values:
    - commonImagePrefix: {{ env "IMAGE_PREFIX" | default "local" }}
    - commonImageTag: latest
  stable:
    values:
    - commonImagePrefix: {{ env "IMAGE_PREFIX" | default "local" }}
    - commonImageTag: v0.0.0

repositories:
- name: stable
  url: https://charts.helm.sh/stable/

releases:

- name: fibo
  chart: ./charts/app
  values:
  - ./values/fibo.yaml.gotmpl

- name: myservice
  chart: ./charts/app
  values:
  - ./values/myservice.yaml.gotmpl

- name: ingress-backend
  chart: stable/nginx-ingress
  version: 1.36.0

- name: ingress-controller
  chart: ./charts/ingress
  values:
  - ./values/ingress.yaml.gotmpl